management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  #服务端口号
  port: 8080

spring:
  data:
    #MongoDB configuration
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27018,mongo3:27019/?replicaSet=rs0
      database: oomall
  jackson:
    #JSON的时间数据的时区
    time-zone: GMT+8

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG


